build:
  maxIssues: 0
  excludeCorrectable: false

complexity:
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    thresholdInClasses: 10
  LongMethod:
    active: true
    threshold: 40
  LargeClass:
    active: true
    threshold: 400

style:
  MaxLineLength:
    active: true
    maxLineLength: 120
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2']
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: true
    ignoreAnnotation: true

naming:
  FunctionNaming:
    active: true
    functionPattern: '[a-z][a-zA-Z0-9]*'
  ClassNaming:
    active: true
    classPattern: '[A-Z][a-zA-Z0-9]*'

