name: Deploy DEV to Firebase

on:
  workflow_dispatch: 
    inputs:
      releaseNotes:
        description: 'O que há de novo nessa versão de testes?'
        required: false
        default: 'Nova versão de Dev para testes internos.'

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Decode google-services.json
        run: |
          mkdir -p Main
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > Main/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # ---------------------------
      # Build LayerNews DEV APK
      # ---------------------------
      - name: Build LayerNews Dev APK
        run: ./gradlew assembleLayerNewsDebug

      - name: List LayerNews APK outputs
        run: ls -lh Main/build/outputs/apk/LayerNews/debug

      - name: Upload LayerNews to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_NEWS }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          groups: testers
          file: Main/build/outputs/apk/LayerNews/debug/Main-LayerNews-debug.apk
          releaseNotes: ${{ github.event.inputs.releaseNotes }}

      # ---------------------------
      # Build LayerSports DEV APK
      # ---------------------------
      - name: Build LayerSports Dev APK
        run: ./gradlew assembleLayerSportsDebug

      - name: List LayerSports APK outputs
        run: ls -lh Main/build/outputs/apk/LayerSports/debug

      - name: Upload LayerSports to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID_SPORTS }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
          groups: testers
          file: Main/build/outputs/apk/LayerSports/debug/Main-LayerSports-debug.apk
          releaseNotes: ${{ github.event.inputs.releaseNotes }}
